# Generated by Django 3.1.1 on 2020-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='ABC'),
            preserve_default=False,
        ),
    ]
