# Generated by Django 3.1.1 on 2020-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_post'),
        ('Post', '0006_auto_20201112_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostTag',
            field=models.ManyToManyField(blank=True, null=True, to='tag.Tag'),
        ),
    ]
