# Generated by Django 3.1.1 on 2020-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_post_posttag'),
        ('tag', '0003_remove_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, to='Post.Post'),
        ),
    ]
