# Generated by Django 3.1.1 on 2020-11-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
    ]
