# Generated by Django 3.1.1 on 2021-02-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_remove_tag_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
